### ISSUE TITLE
Follow position of div for positioning the BrowserView.

### ISSUE THREAD

**Issue by ivanjeremic** [vantezzen/react-electron-browser-view#1]
Across the Internet, there are lots of posts on how to easily embed & position BrowserView same like WebView and people are confused about it since BrowserViews are positioned like this,
 `view.setBounds({ x: 0, y: 0, width: 300, height: 300 })` 

So my idea was maybe we can have a simple `<div id="browserview"><div/>`

And a feature in this project to detect & follow always this div with the id and calculate the Bounds/width/height the BrowserView needs to have.

I'm curious if this would be possible, I would love to hear opinions and to help in this repo but somehow I don't know where to start and I would love someone to look at this idea and hear other opinions.

**Comment by vantezzen** [comment]
I mean this is exactly what this package is doing? This package is internally creating a div:

https://github.com/vantezzen/react-electron-browser-view/blob/f7bd112aff512fdb41e43fb9a385fd49d2382fa5/src/ElectronBrowserView.js#L167-L175

It then uses this div plus some "React magic" to set the bounds of the BrowserView:

https://github.com/vantezzen/react-electron-browser-view/blob/f7bd112aff512fdb41e43fb9a385fd49d2382fa5/src/ElectronBrowserView.js#L136-L163

https://github.com/vantezzen/react-electron-browser-view/blob/f7bd112aff512fdb41e43fb9a385fd49d2382fa5/src/ElectronBrowserView.js#L153

It is just that it isn't just a `<div id="browserview"><div/>` but a React component as I build the whole package to be a replacement for https://github.com/MarshallOfSound/react-electron-web-view - that's why the name is "**react**-electron-browser-view" 😅.

If you want to, you can take the code in https://github.com/vantezzen/react-electron-browser-view/tree/master/src, remove all the React parts of it and publish that as a new NPM package.

**Comment by ivanjeremic** [comment]
I found the problem I was facing back then, The BrowserView gets only 100% in height & width when I make it a separate component without any surroundings, so all I return is the component I get from your package, surrounding it in any way with a div or using it directly in the UI where it should fill only a part with full height & width will not work. But as I said returning it from a component & then use it works like a charm, no idea why I tried to figure it out.

**Comment by vantezzen** [comment]
This sounds like it might have been a problem with the default style the internal `div` gets:

https://github.com/vantezzen/react-electron-browser-view/blob/f7bd112aff512fdb41e43fb9a385fd49d2382fa5/src/ElectronBrowserView.js#L171-L173

You can overwrite that using the `style` props if you need these properties to behave differently, like:

```JavaScript
<BrowserView style={{
width: 'auto',
height: 'auto',
}}
/>
```

**Comment by ivanjeremic** [comment]
Thanks, What do you think about https://github.com/brrd/electron-tabs I would like somehow to get your package to do tab stuff also, have you any advice what the best way would be, not active tabs should still have the state they had before even when swiching?

**Comment by vantezzen** [comment]
I think the best way to implement tabs with BrowserViews is to keep all BrowserViews open but hiding all but the current one using `display: none;`. This way, the views keep their state but you don't see them.

This is also how we at [Ferdi](https://getferdi.com) manage the tabs by the way (it's a little more difficult to see there as the data is spread across files and stored in MobX stores but the concept is the same):

https://github.com/getferdi/ferdi/blob/6999476b9eb71880e16b413f27a7df5bf458cd47/src/components/services/content/Services.js#L171-L190
